### ISSUE TITLE
Unreadable form

### ISSUE THREAD

**Issue by MarkSwanson** [marick/Midje#197]
I can run all of my midje tests from the repl (vimclojure) but 'lein midje' fails with 'Unreadable form'.

I've tried with leiningen 2.0.0 and 2.1.0-SNAPSHOT.
I'm running midje 1.5.0, lein-midje 3.0.0, clojure 1.5.1 (same results with 1.5.0 and 1.4.0) on Ubuntu 12.10.

lein --version
WARNING: user-level profile defined in project files.
Leiningen 2.1.0-SNAPSHOT on Java 1.7.0 Java HotSpot(TM) 64-Bit Server VM

lein midje
WARNING: user-level profile defined in project files.
Exception in thread "main" clojure.lang.LispReader$ReaderException: java.lang.RuntimeException: Unreadable form
	at clojure.lang.LispReader.read(LispReader.java:220)
	at clojure.core$read.invoke(core.clj:3407)
	at clojure.core$read.invoke(core.clj:3405)
	at clojure.main$eval_opt$fn__6618.invoke(main.clj:306)
	at clojure.main$eval_opt.invoke(main.clj:306)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main$fn__6661.invoke(main.clj:440)
	at clojure.main$main.doInvoke(main.clj:437)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unreadable form
	at clojure.lang.Util.runtimeException(Util.java:219)
	at clojure.lang.LispReader$UnreadableReader.invoke(LispReader.java:1116)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:626)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1091)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.read(LispReader.java:185)
	... 13 more

**Comment by ghoseb** [comment]
Bump! This bug still exists in Midje.

**Comment by ghoseb** [comment]
This seems to be more of a problem with `lein-midje`. For now I have fixed it like so: ghoseb/lein-midje@558386e6069104233e5a02113c4436da96f548c0 but I would be interested in a more general fix.

**Comment by marick** [comment]
Do you have a project file that fails?

All of the lein midje stuff suffers from my having copied code I didn't understand or obeyed instructions I didn't understand. Might be worth looking at how runners for Expectations or other unit test frameworks work. (clojure.test has - or had - a lot of direct support in Leiningen itself.)

**Comment by dmac** [comment]
Yes, the project file I included above still fails with the latest versions and lein 2.5.1.

```clojure
(defproject lein-midje-unreadabe-form "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [midje "1.6.3"]]
  :plugins [[lein-midje "3.1.3"]]
  :manifest {"Project-Name" ~#(:group %)})
```

```
$ lein midje
Exception in thread "main" java.lang.RuntimeException: Unreadable form, compiling:(/private/var/folders/c3/ctpg5cqn37z90k0986yqnhgm0000gn/T/form-init7499177969449398545.clj:1:1310)
	at clojure.lang.Compiler.load(Compiler.java:7071)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unreadable form
	at clojure.lang.Util.runtimeException(Util.java:219)
	at clojure.lang.LispReader$UnreadableReader.invoke(LispReader.java:1116)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:626)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1091)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1091)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1148)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:982)
	at clojure.lang.LispReader.read(LispReader.java:185)
	at clojure.lang.Compiler.load(Compiler.java:7060)
	... 11 more
Subprocess failed
```

**Comment by dmac** [comment]
Were you able to resolve this issue? I still get an error with the above minimal project.clj and running `lein midje` with the latest versions of lein, midje, and lein-midje; though it's a different exception now:

```
Exception in thread "main" java.lang.RuntimeException: No reader function for tag object, compiling: ...
```

**Comment by marick** [comment]
To make progress on this, I'll need a project that I can download or `git clone` that exhibits the failure.

**Comment by dmac** [comment]
I've made a minimal example available at [dmac/lein-midje-bug-report](https://github.com/dmac/lein-midje-bug-report). To reproduce the issue you can git clone it and run `lein midje`. Note that the exception is different from the one this bug report was opened with, presumably because an update of lein or midje changed the exception exposed to the user.

**Comment by marick** [comment]
Fixed with `lein-midje` 3.2.1
